### ISSUE TITLE
Pyreconstruct Fails to Open After Update

### ISSUE THREAD

**Issue by AndrewLyon** [SynapseWeb/PyReconstruct#22]
**Describe the bug**
Update PyReconstruct --  now get error with "first_open"
**To Reproduce**
1. update preconstruct with pyreconstruct --update
2. call pyreconstruct to open
3. pyreconstruct errors

**Expected behavior**
Pyreconstruct should open

**Screenshots**
see attached
error:
<img width="831" alt="Screenshot 2024-03-19 at 12 43 54 PM" src="https://github.com/SynapseWeb/PyReconstruct/assets/143132070/45f5dfc4-46e9-468a-b85e-1d0eef27e114">

Traceback (most recent call last):
  File "/Users/drew/miniconda3/bin/pyreconstruct", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/drew/miniconda3/lib/python3.11/site-packages/PyReconstruct/cli.py", line 13, in main
    open_file(args.filename)
  File "/Users/drew/miniconda3/lib/python3.11/site-packages/PyReconstruct/cli.py", line 18, in open_file
    runPyReconstruct(filename)
  File "/Users/drew/miniconda3/lib/python3.11/site-packages/PyReconstruct/run.py", line 33, in runPyReconstruct
    main_window = main.MainWindow(filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/miniconda3/lib/python3.11/site-packages/PyReconstruct/modules/gui/main/main_window.py", line 128, in __init__
    self.openSeries(welcome_series)
  File "/Users/drew/miniconda3/lib/python3.11/site-packages/PyReconstruct/modules/gui/main/main_window.py", line 991, in openSeries
    if not first_open:
           ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'first_open' where it is not associated with a value

**Desktop (please complete the following information):**
 - OS: Windows and MacOs
 - Version W10, MacOS 14.4

**Python (please indicate the version of Python you are using):**
- Version 3.11

**Additional context**
updated pyreconstruct this morning on a lab PC, error occurred after the update. Ran the update process on my mac and received the same result.

**Comment by quasiTriestino** [comment]
@AndrewLyon I've patched `openSeries` method in `main_window.py` to before the introduction of the `first_open` variable with commit 015dacf. This should fix the issue for you (I hope); however, I am able to open PyReconstruct fine on my end even with these changes, which means likely something else is going on with your specs that we should probably investigate. Can you open PyReconstruct with the most recent commit?

**Comment by AndrewLyon** [comment]
Everything has been updated and runs on my end, thank you!
