### ISSUE TITLE
3D object generation fails

### ISSUE THREAD

**Issue by AndrewLyon** [SynapseWeb/PyReconstruct#34]
### Describe the bug
When adding a traced object to a 3D scene to view, error occurs and object generation fails.

### Commit or version

752fb46

### To Reproduce

Lists > Object list > choose an object > right click and go to 3D > add to scene > error

### Expected behavior

3D object rendered to scene

### Desktop environment:

macos 14.6.1 (arm64)

### Python version

3.11.9

### Error messages

Traceback (most recent call last):
  File "/Users/drew/miniconda3/envs/test/lib/python3.11/site-packages/PyReconstruct/modules/gui/main/field_widget_3_object.py", line 104, in wrapper
    completed = fn(self, selected_names, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/miniconda3/envs/test/lib/python3.11/site-packages/PyReconstruct/modules/gui/main/field_widget_3_object.py", line 301, in addTo3D
    self.mainwindow.addTo3D(obj_names)
  File "/Users/drew/miniconda3/envs/test/lib/python3.11/site-packages/PyReconstruct/modules/gui/main/main_window.py", line 2132, in addTo3D
    self.viewer = CustomPlotter(self, names, ztraces)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/miniconda3/envs/test/lib/python3.11/site-packages/PyReconstruct/modules/gui/popup/custom_plotter.py", line 703, in __init__
    self.screen_info = mainwindow.screen_info  # info about primary screen
                       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'screen_info'

### Additional context

Fails within a new environment, with conda installing git and pip installing everything else.

**Comment by quasiTriestino** [comment]
Sorry about that -- I have fixed this as of commit d823acc. Give it a go and let me know if it works.

**Comment by AndrewLyon** [comment]
Fixed, thank you!
